# Generated by Django 3.0.7 on 2020-07-10 18:22

from django.db import migrations, models
import shortener.validators


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0002_auto_20200702_1706'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=240)),
                ('email', models.EmailField(max_length=254)),
                ('content', models.TextField(max_length=4000)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='wjurl',
            name='url',
            field=models.CharField(max_length=240, validators=[shortener.validators.validate_url]),
        ),
    ]
