# Generated by Django 3.0.7 on 2020-07-11 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0003_auto_20200710_2322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='username',
            field=models.CharField(blank=True, max_length=240, null=True),
        ),
    ]
